Repository iPho4ticket/backend, pull requests merged in 2024-10, with the labels that each got.

#19 :tada: Auth 모듈 초기 설정
  auth-service/build.gradle
  auth-service/src/main/java/com/ticketing/authservice/AuthServiceApplication.java
  auth-service/src/main/resources/application.properties
  auth-service/src/test/java/com/ticketing/authservice/AuthServiceApplicationTests.java
  settings.gradle
Labels: ⚙️ Setting

#20 ✨ 결제 기본 api 구현
  payment-service/src/main/java/com/ipho4ticket/paymentservice/PaymentServiceApplication.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/model/Payment.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/model/PaymentMethod.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/repository/CustomPaymentRepository.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/repository/JpaPaymentRepository.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/request/PaymentRequestDTO.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/response/PaymentResponseDTO.java
  payment-service/src/test/java/com/ipho4ticket/paymentservice/PaymentServiceTest.java
  payment-service/src/test/java/com/ipho4ticket/paymentservice/ReflectionUtils.java
Labels: ✨ Feature

#15 :sparkles: 이벤트 기본 API 개발
  buildSrc/src/main/groovy/query-dsl-conventions.gradle
  event-service/build.gradle
  event-service/src/main/java/com.ipho4ticket.eventservice/EventServiceApplication.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/dto/EventDto.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/service/EventService.java
  event-service/src/main/java/com.ipho4ticket.eventservice/domain/model/BaseEntity.java
  event-service/src/main/java/com.ipho4ticket.eventservice/domain/model/Event.java
  event-service/src/main/java/com.ipho4ticket.eventservice/domain/repository/EventRepository.java
  event-service/src/main/java/com.ipho4ticket.eventservice/infra/config/QuerydslConfig.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/controller/EventController.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/except/EventNotFoundException.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/except/GlobalExceptionHandler.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/request/EventRequest.java
  event-service/src/main/resources/application.yml
  event-service/src/test/java/com/ipho4ticket/eventservice/EventServiceApplicationTests.java
  event-service/src/test/java/com/ipho4ticket/eventservice/EventServiceTest.java
  settings.gradle
Labels: ✨ Feature

#26 :sparkles: 공통 모듈 구성 + ticket 구조 수정
  common/build.gradle
  common/src/main/java/com/ipho/common/auditor/AuditorAwareConfig.java
  common/src/main/java/com/ipho/common/auditor/AuditorAwareImpl.java
  common/src/main/java/com/ipho/common/auditor/BaseEntity.java
  common/src/main/java/com/ipho/common/exception/ErrorResponse.java
  common/src/main/java/com/ipho/common/exception/GlobalExceptionHandler.java
  common/src/main/resources/application.yml
  settings.gradle
  ticket-service/build.gradle
  ticket-service/src/main/java/com/ipho/ticketservice/application/dto/TicketInfoDto.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/service/TicketService.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/model/Ticket.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/model/TicketStatus.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/service/TicketDomainService.java
  ticket-service/src/main/java/com/ipho/ticketservice/infrastructure/repository/JpaTicketRepository.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/controller/TicketController.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/request/TicketRequestDto.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/response/TicketResponseDto.java
  ticket-service/src/main/resources/application.yml
  ticket-service/src/test/java/com/ipho/ticketservice/TicketServiceTest.java
Labels: 🔨 Refactor, ⚙️ Setting

#27 ✨ 알림 기본 api 구현
  notification-service/build.gradle
  notification-service/src/main/java/com/ipho4ticket/notificationservice/application/service/NotificationService.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/domain/model/Notification.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/domain/model/NotificationStatus.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/domain/model/NotificationType.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/domain/repository/NotificationRepository.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/infrastructure/configuration/DataSourceConfig.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/infrastructure/configuration/JpaConfig.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/presentation/controller/NotificationController.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/presentation/request/NotificationRequestDTO.java
  notification-service/src/main/java/com/ipho4ticket/notificationservice/presentation/response/NotificationResponseDTO.java
  notification-service/src/main/resources/application.properties
  notification-service/src/main/resources/application.yml
  notification-service/src/test/java/com/ipho4ticket/notificationservice/NotificationServiceTest.java
Labels: ✨ Feature

#24 ✨ 인증 서비스 기본 유틸리티 추가
  auth-service/build.gradle
  auth-service/src/main/java/com/ticketing/authservice/AuthServiceApplication.java
  auth-service/src/main/java/com/ticketing/authservice/application/dto/UserDto.java
  auth-service/src/main/java/com/ticketing/authservice/application/mapper/AuthDataMapper.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/client/UserFeignClient.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/client/UserFeignService.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/common/RoleType.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/security/BCryptUtil.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/security/JwtUtil.java
  auth-service/src/main/resources/application.properties
  auth-service/src/main/resources/application.yml
  auth-service/src/test/resources/application.yml
Labels: ✨ Feature, ⚙️ Setting

#28 ✨ 좌석 기본 api 구현
  seat-service/build.gradle
  seat-service/src/main/java/com/ipho4ticket/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/dto/SeatResponseDto.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/model/BaseEntity.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/model/Seat.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/model/SeatStatus.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/repository/SeatRepository.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/presentation/request/SeatRequestDto.java
  seat-service/src/main/resources/application.yml
  seat-service/src/test/java/com/ipho4ticket/seatservice/SeatServiceApplicationTests.java
  seat-service/src/test/java/com/ipho4ticket/seatservice/SeatServiceTest.java
  settings.gradle
Labels: ✨ Feature

#35 :tada: 게이트웨이 모듈 초기 설정
  gateway-service/build.gradle
  gateway-service/src/main/java/com/ticketing/gatewayservice/GatewayServiceApplication.java
  gateway-service/src/main/resources/application.properties
  gateway-service/src/test/java/com/ticketing/gatewayservice/GatewayServiceApplicationTests.java
  settings.gradle
Labels: ⚙️ Setting

#32 ✨ 인증 서비스 API 구현
  auth-service/src/main/java/com/ticketing/authservice/application/service/AuthService.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/common/CustomException.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/common/codes/ErrorCode.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/common/codes/ResponseCode.java
  auth-service/src/main/java/com/ticketing/authservice/presentation/controller/AuthController.java
  auth-service/src/test/java/com/ticketing/authservice/application/service/AuthServiceTest.java
  auth-service/src/test/java/com/ticketing/authservice/infrastructure/helper/ArbitraryUserFactory.java
  auth-service/src/test/java/com/ticketing/authservice/infrastructure/helper/util/ArbitraryField.java
  auth-service/src/test/java/com/ticketing/authservice/infrastructure/security/JwtUtilTest.java
Labels: ✨ Feature, ✅ Test

#33 :art: pr반영_event 코드 수정, common 모듈 적용
  event-service/build.gradle
  event-service/src/main/java/com.ipho4ticket.eventservice/EventServiceApplication.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/dto/EventDto.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/dto/EventResponseDto.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/service/EventService.java
  event-service/src/main/java/com.ipho4ticket.eventservice/domain/model/BaseEntity.java
  event-service/src/main/java/com.ipho4ticket.eventservice/domain/model/Event.java
  event-service/src/main/java/com.ipho4ticket.eventservice/domain/repository/EventRepository.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/controller/EventController.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/except/EventNotFoundException.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/except/GlobalExceptionHandler.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/request/EventRequest.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/request/EventRequestDto.java
  event-service/src/test/java/com/ipho4ticket/eventservice/EventServiceTest.java
  seat-service/build.gradle
  seat-service/src/main/java/com/ipho4ticket/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/config/RedisConfig.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/dto/SeatResponseDto.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/model/BaseEntity.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/model/Seat.java
  seat-service/src/main/resources/application.yml
  seat-service/src/test/java/com/ipho4ticket/seatservice/SeatServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#38 :sparkles: Payment -> Ticket 내부 통신 모듈
  client-ticket-feign/build.gradle
  client-ticket-feign/src/main/java/com/ipho4ticket/clientticketfeign/ClientTicketFeign.java
  client-ticket-feign/src/main/java/com/ipho4ticket/clientticketfeign/TicketConfig.java
  client-ticket-feign/src/main/java/com/ipho4ticket/clientticketfeign/dto/ValidationResponse.java
  client-ticket-feign/src/main/resources/client-ticket.yml
  settings.gradle
Labels: ⚙️ Setting

#43 ✨ Seat -> Event 내부 통신
  client-event-feign/build.gradle
  client-event-feign/src/main/java/com/ipho4ticket/clienteventfeign/ClientEventFeign.java
  client-event-feign/src/main/java/com/ipho4ticket/clienteventfeign/EventConfig.java
  client-event-feign/src/main/java/com/ipho4ticket/clienteventfeign/dto/EventResponseDto.java
  client-event-feign/src/main/resources/application.yml
  event-service/src/main/java/com.ipho4ticket.eventservice/application/service/EventService.java
  event-service/src/main/java/com.ipho4ticket.eventservice/domain/model/Event.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/controller/EventInternalController.java
  event-service/src/main/resources/application.yml
  event-service/src/test/java/com/ipho4ticket/eventservice/EventServiceTest.java
  seat-service/build.gradle
  seat-service/src/main/java/com/ipho4ticket/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/events/CancelPaymentEvent.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/events/SeatBookingEvent.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/events/TicketMakingEvent.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/EventProducer.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/infra/messaging/EventConsumer.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/infra/messaging/EventSerializer.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/resources/application.yml
  seat-service/src/test/java/com/ipho4ticket/seatservice/SeatServiceApplicationTests.java
  seat-service/src/test/java/com/ipho4ticket/seatservice/SeatServiceTest.java
  settings.gradle
Labels: ✨ Feature, ✅ Test

#47 ✨ 게이트웨이 서버 기본 유틸 추가
  gateway-service/build.gradle
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/configuration/SecurityConfig.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/configuration/SystemConfigService.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/feign/AuthWebClient.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/handler/AuthTokenResponseHandler.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/util/CacheUtils.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/util/TokenUtils.java
  gateway-service/src/main/resources/application.properties
  gateway-service/src/main/resources/application.yml
Labels: ⚙️ Setting

#51 ✨ 게이트웨이 기본 서비스 구현
  gateway-service/src/main/java/com/ticketing/gatewayservice/application/filter/AuthTokenFilter.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/application/filter/DenyAccessGatewayFilter.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/cache/CacheService.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/cache/CaffeineCacheService.java
  gateway-service/src/test/java/com/ticketing/gatewayservice/application/filter/AuthTokenFilterTest.java
  gateway-service/src/test/java/com/ticketing/gatewayservice/application/filter/DenyAccessGatewayFilterTest.java
  gateway-service/src/test/java/com/ticketing/gatewayservice/infrastructure/cache/CaffeineCacheServiceTest.java
  gateway-service/src/test/java/com/ticketing/gatewayservice/infrastructure/helper/ArbitraryClaimsFactory.java
  gateway-service/src/test/java/com/ticketing/gatewayservice/infrastructure/helper/ArbitraryExchangeFactory.java
  gateway-service/src/test/resources/application.yml
Labels: ✨ Feature, ✅ Test

#45 ✨ 카카오페이 연동
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/dto/ApproveResponse.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/dto/ReadyResponse.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/factory/PaymentProcessorFactory.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/model/Payment.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/model/PaymentMethod.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/model/PaymentStatus.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/service/PaymentDomainService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/service/PaymentProcessor.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/external/KakaoPayService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/resources/application.yml
  payment-service/src/test/java/com/ipho4ticket/paymentservice/PaymentServiceTest.java
Labels: ✨ Feature

#58 ⚙️ 인증 서비스 dockerfile 추가
  auth-service/Dockerfile
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/client/UserFeignClient.java
Labels: 🐞 bug, ⚙️ Setting

#61 ⚙️ 게이트웨이 서비스 dockerfile 추가 및 버그 수정
  gateway-service/Dockerfile
  gateway-service/src/main/java/com/ticketing/gatewayservice/application/filter/AuthTokenFilter.java
  gateway-service/src/main/resources/application.yml
Labels: 🐞 bug, ⚙️ Setting

#64 ✨ 유저 서비스 내부통신 API 및 dockerfile 추가
  user-service/Dockerfile
  user-service/build.gradle
  user-service/src/main/java/com/ticketing/userservice/application/dto/UserDto.java
  user-service/src/main/java/com/ticketing/userservice/application/dto/UserMapper.java
  user-service/src/main/java/com/ticketing/userservice/application/service/UserService.java
  user-service/src/main/java/com/ticketing/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/ticketing/userservice/presentation/UserInternalController.java
  user-service/src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting

#73 ✨ kakao 결제 parameter 수정 및 feign 추가
  client-ticket-feign/src/main/java/com/ipho4ticket/clientticketfeign/ClientTicketFeign.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/external/KakaoPayService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/test/java/com/ipho4ticket/paymentservice/PaymentServiceTest.java
Labels: ✨ Feature

#71 ✨ docker compose 생성
  client-event-feign/src/main/resources/application.yml
  client-event-feign/src/main/resources/client-event.yml
  event-service/Dockerfile
  event-service/docker-compose.yml
  event-service/src/main/resources/application-dev.yml
  event-service/src/main/resources/application-prod.yml
  event-service/src/main/resources/application.yml
  seat-service/Dockerfile
  seat-service/docker-compose.yml
  seat-service/src/main/java/com/ipho4ticket/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/model/Seat.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/resources/application-dev.yml
  seat-service/src/main/resources/application-prod.yml
  seat-service/src/main/resources/application.yml
  seat-service/src/test/java/com/ipho4ticket/seatservice/SeatServiceTest.java
Labels: ⚙️ Setting, ✅ Test

#67 :memo: ticket service dockerfile 추가
  ticket-service/Dockerfile
  ticket-service/src/test/java/com/ipho/ticketservice/service/EventProducerTest.java
Labels: 📝 Docs, ⚙️ Setting

#81 ✨ 결제 취소
  client-ticket-feign/src/main/java/com/ipho4ticket/clientticketfeign/ClientTicketFeign.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/dto/PaymentInfoResponse.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/factory/PaymentProcessorFactory.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/service/PaymentProcessor.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/external/KakaoPayService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/response/PaymentResponseDTO.java
  payment-service/src/test/java/com/ipho4ticket/paymentservice/PaymentServiceTest.java
Labels: ✨ Feature

#90 🐞 게이트웨이 캐시 미스시 불필요한 Baerer 추가 제거
  gateway-service/src/main/java/com/ticketing/gatewayservice/application/filter/AuthTokenFilter.java
  gateway-service/src/main/resources/application.yml
Labels: 🐞 bug, ⚙️ Setting

#87 ♻️ 결제 리팩토링
  client-ticket-feign/src/main/java/com/ipho4ticket/clientticketfeign/ClientTicketFeign.java
  payment-service/build.gradle
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/configuration/DataSourceConfig.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/external/KakaoPayService.java
  payment-service/src/main/resources/application.yml
Labels: 🐞 bug, 🔨 Refactor

#69 ✨ 인증 서비스 토큰 검증 내부 통신 API 추가
  auth-service/build.gradle
  auth-service/src/main/java/com/ticketing/authservice/application/service/AuthService.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/common/CustomException.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/common/codes/ErrorCode.java
  auth-service/src/main/java/com/ticketing/authservice/infrastructure/security/JwtUtil.java
  auth-service/src/main/java/com/ticketing/authservice/presentation/controller/AuthInternalController.java
  auth-service/src/test/java/com/ticketing/authservice/application/service/AuthServiceTest.java
Labels: ✨ Feature, ✅ Test

#88 Feat/86 ticket service dymamic topic create and test
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/dto/TicketMakingEvent.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/dto/TicketTopic.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/service/EventConsumer.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/service/EventProducer.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/service/TicketService.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/model/Ticket.java
  ticket-service/src/main/java/com/ipho/ticketservice/infrastructure/messaging/DynamicKafkaListener.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/controller/TicketController.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/controller/TicketInternalController.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/EventProducerTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceTest.java
  ticket-service/src/test/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#96 Feat/95 ticket feign 추가 구현 및 테스트 eventdto 수정
  common/src/main/java/com/ipho/common/exception/ErrorResponse.java
  common/src/main/java/com/ipho/common/exception/GlobalExceptionHandler.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/dto/SeatBookingEvent.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/service/EventProducer.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/service/TicketService.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/controller/TicketInternalController.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/exception/TicketException.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/exception/TicketExceptionHandler.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/exception/ValidationException.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/EventProducerTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketInternalMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#100 Feat/93 상품이름추가
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
Labels: 🔨 Refactor

#102 🐞 결제 테스트 버그
  payment-service/build.gradle
  payment-service/src/test/java/com/ipho4ticket/paymentservice/PaymentServiceTest.java
Labels: 🐞 bug

#108 :recycle: 카카오페이 경로 수정
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/external/KakaoPayService.java
  payment-service/src/main/resources/application.yml
Labels: 🔨 Refactor

#107 Feat/106
  common/src/main/java/com/ipho/common/dto/CancelTicketEvent.java
  common/src/main/java/com/ipho/common/dto/ConfirmSeatEvent.java
  common/src/main/java/com/ipho/common/dto/SeatBookingEvent.java
  common/src/main/java/com/ipho/common/dto/TicketMakingEvent.java
  settings.gradle
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/EventProducer.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/event/TicketTopic.java
  ticket-service/src/main/java/com/ipho/ticketservice/application/service/TicketService.java
  ticket-service/src/main/java/com/ipho/ticketservice/infrastructure/client/SeatClientService.java
  ticket-service/src/main/java/com/ipho/ticketservice/infrastructure/messaging/DynamicKafkaListener.java
  ticket-service/src/main/resources/application.yml
  ticket-service/src/test/java/com/ipho/ticketservice/service/EventProducerTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketInternalMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceTest.java
Labels: 🔨 Refactor

#113 Feat/112
  client-event-feign/build.gradle
  client-ticket-feign/build.gradle
  common/src/main/java/com/ipho/common/dto/TicketMakingEvent.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/EventProducer.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/SeatService.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/model/Ticket.java
Labels: 🔨 Refactor

#119 :bug: 중복 결제 수정
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/model/Payment.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/external/KakaoPayService.java
Labels: 🐞 bug

#118 :bug: 게이트웨이 테스트 오류 수정
  gateway-service/src/test/java/com/ticketing/gatewayservice/application/filter/AuthTokenFilterTest.java
Labels: 🐞 bug, ✅ Test

#121 ♻️ 좌석 서비스 오류 수정
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/exception/EventNotExistsException.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/exception/GlobalExceptionHandler.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/exception/SeatAlreadyExistsException.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/application/service/exception/SeatNotExistsException.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/domain/model/Seat.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/presentation/request/SeatRequestDto.java
  seat-service/src/main/resources/application.yml
  seat-service/src/test/java/com/ipho4ticket/seatservice/SeatServiceTest.java
Labels: 🐞 bug, 🔨 Refactor, ✅ Test

#131 🎉 인가 모듈 추가
  authz-filter/build.gradle
  authz-filter/src/main/java/com/ticketing/authzfilter/infrastructure/common/CustomException.java
  authz-filter/src/main/java/com/ticketing/authzfilter/infrastructure/common/RoleType.java
  authz-filter/src/main/java/com/ticketing/authzfilter/infrastructure/common/codes/ErrorCode.java
  authz-filter/src/main/java/com/ticketing/authzfilter/infrastructure/common/codes/ResponseCode.java
  authz-filter/src/main/java/com/ticketing/authzfilter/security/RoleHierarchyConfig.java
  authz-filter/src/main/java/com/ticketing/authzfilter/security/SecurityConfig.java
  authz-filter/src/main/java/com/ticketing/authzfilter/security/SecurityUtil.java
  authz-filter/src/main/java/com/ticketing/authzfilter/security/filter/RoleAuthorizationFilter.java
  settings.gradle
Labels: ✨ Feature

#128 Feat/127
  ticket-service/src/main/java/com/ipho/ticketservice/application/service/TicketService.java
  ticket-service/src/main/java/com/ipho/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketInternalMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#125 ♻️ 결재 리팩토링
  common/src/main/java/com/ipho/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/ipho/common/exception/payment/AccessDeniedPaymentException.java
  common/src/main/java/com/ipho/common/exception/payment/InvalidPaymentStatusException.java
  common/src/main/java/com/ipho/common/exception/payment/PaymentNotFoundException.java
  common/src/main/java/com/ipho/common/exception/payment/PaymentProcessingException.java
  common/src/main/java/com/ipho/common/exception/payment/TicketValidationException.java
  payment-service/build.gradle
  payment-service/src/main/java/com/ipho4ticket/paymentservice/PaymentServiceApplication.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/test/java/com/ipho4ticket/paymentservice/PaymentServiceTest.java
Labels: 🔨 Refactor

#133 ✨ 게이트웨이에서 헤더에 인가에 필요한 정보 추가
  gateway-service/src/main/java/com/ticketing/gatewayservice/application/filter/AuthTokenFilter.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/cache/CaffeineCacheService.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/infrastructure/handler/AuthTokenResponseHandler.java
Labels: 🐞 bug, ✨ Feature

#129 ♻️ 이벤트 서비스 리팩토링
  event-service/src/main/java/com.ipho4ticket.eventservice/application/kevents/EventMakingEvent.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/service/EventProducer.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/service/EventService.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/service/exception/GlobalExceptionHandler.java
  event-service/src/main/java/com.ipho4ticket.eventservice/application/service/exception/SearchNotExistsException.java
  event-service/src/main/resources/application.yml
  event-service/src/test/java/com/ipho4ticket/eventservice/EventServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#139 :white_check_mark: event/seat 서비스 인가 모듈 추가
  event-service/build.gradle
  event-service/src/main/java/com.ipho4ticket.eventservice/EventServiceApplication.java
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/controller/EventController.java
  seat-service/build.gradle
  seat-service/src/main/java/com/ipho4ticket/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/ipho4ticket/seatservice/presentation/controller/SeatController.java
Labels: ✨ Feature

#141 :memo: 리드미 추가
  README.md
Labels: 📝 Docs

#140 🎇 결제 인가 및 로직 수정
  payment-service/build.gradle
  payment-service/src/main/java/com/ipho4ticket/paymentservice/PaymentServiceApplication.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/domain/service/PaymentProcessor.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/infrastructure/external/KakaoPayService.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/ipho4ticket/paymentservice/presentation/request/PaymentRequestDTO.java
  payment-service/src/test/java/com/ipho4ticket/paymentservice/PaymentServiceTest.java
Labels: 🐞 bug, ✨ Feature

#142 :white_check_mark: event서비스 @PreAuthorize 삭제
  event-service/src/main/java/com.ipho4ticket.eventservice/presentation/controller/EventController.java
Labels: 🔨 Refactor

#145 🐛 결제 승인 리다이렉트 토큰 검증 제외
  authz-filter/src/main/java/com/ticketing/authzfilter/security/SecurityConfig.java
  gateway-service/src/main/java/com/ticketing/gatewayservice/application/filter/AuthTokenFilter.java
  gateway-service/src/test/java/com/ticketing/gatewayservice/infrastructure/helper/ArbitraryClaimsFactory.java
Labels: 🐞 bug, ✅ Test

#148 :memo: 인프라 구조도 이미지 변경
  README.md
Labels: 📝 Docs

#150 :bug: 인증 모듈 URI 의 누락된 표현식 추가
  auth-service/src/main/java/com/ticketing/authservice/presentation/controller/AuthController.java
  auth-service/src/main/java/com/ticketing/authservice/presentation/controller/AuthInternalController.java
Labels: 🐞 bug

#147 Feat/146
  ticket-service/build.gradle
  ticket-service/src/main/java/com/ipho/ticketservice/application/service/TicketService.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/controller/TicketController.java
  ticket-service/src/main/java/com/ipho/ticketservice/presentation/request/TicketRequestDto.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceMockTest.java
  ticket-service/src/test/java/com/ipho/ticketservice/service/TicketServiceTest.java
Labels: 🔨 Refactor
